name: python36
channels:
  - conda-forge
  - defaults
dependencies:
  - av
  - glob
  - h5py
  - jupyter
  - imageio
  - jupyterlab
  - numpydoc
  - OpenPIV
  - pandas
  - python=3.6.6
  - tqdm
  - bokeh
  - matplotlib
  - numpy
  - scikit-image
  - scipy
  - sphinx
  - nb-conda-kernels
  - pip:
    - bebi103
    - czifile
    - sphinx-rtd-theme
    - tifffile

